### ISSUE TITLE
Possible bug in Segmentation Step

### ISSUE THREAD

**Issue by Umar-Ayub** [BII-wushuang/FLLIT#2]
Hello,

I am running the gui and managed to load a data folder. However when I press the Segmentation button the program halts and the following traceback is received from the Matlab console. Any feedback on this issue would be appreciated:

### Traceback
Error using mkdir
No such file or directory

Error in FLLIT>Segmentation_Callback (line 812)
    mkdir(output_dir);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in FLLIT (line 47)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FLLIT('Segmentation_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by BII-wushuang** [comment]
Hi, the image data that you would like to process should be placed inside a ```Data``` folder (a shortcut / symbolic link works as well, but it has to be named ```Data```) in the directory where you are running FLLIT.

The folder organisation would look some like this ```FLLIT Directory/Data/Your Data Folders``` where ```FLLIT Directory``` is where you are executing FLLIT from.
