### ISSUE TITLE
MacOS running problem

### ISSUE THREAD

**Issue by lvhailong** [BII-wushuang/FLLIT#3]
Hello, I have followed the instructions in readme file to install Docker.dmg and XQuartz-2.7.11.dmg. 
But I cannot run it. Here is my terminal's feedback:
```

lvhailongdeiMac:Compiled lvhailong$ docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=172.30.67.33:0 feijianke/fllit
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64

```
It just stop here and nothing happen.

**Comment by BII-wushuang** [comment]
Hi, please make sure that you have already issued the **socat command in terminal**
```socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown```
and **XQuartz is running** before issuing your docker run command
```docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=172.30.67.33:0 feijianke/fllit```

I just gave it a try and things should be working fine. Please give it a try and let me know if everything is alright.

**Comment by lvhailong** [comment]
Thanks for your reply. Now I can run it on macOS. However, After I clicked the segmentation button. The program used a lot of CPU and then the window was crashed and closed automatically .
Here is the logs in terminal:
```
Last login: Wed Jul 31 14:58:47 on console
lvhailongdeiMac:~ lvhailong$ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown
[1] 540
lvhailongdeiMac:~ lvhailong$ docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=166.111.152.226:0 feijianke/fllit
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
Opening log file:  /root/java.log.9
FLLIT: javainit.cpp:1389: void {anonymous}::mwJavaAbort(): Assertion `Fatal Java Exception.  See Java Crash Report for details.' failed.

------------------------------------------------------------------------
             Assertion detected at Wed Jul 31 07:19:03 2019
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled
  Crash Mode          : continue (default)
  Current Graphics Driver: Brian Paul Mesa X11 Version 2.1 Mesa 10.5.2
  Current Visual      : 0x22 (class 4, depth 24)
  Default Encoding    : US-ASCII
  GNU C Library       : 2.23 stable
  Host Name           : cb40b7649641
  Java Crash Report   : /root/hs_error_pid9.log
  Java Log            : /root/java.log.9
  MATLAB Architecture : glnxa64
  MATLAB Root         : /opt/mcr/v901
  MATLAB Version      : 9.0.0.341360 (R2016a)
  OpenGL              : hardware
  Operating System    : Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
  Processor ID        : x86 Family 6 Model 58 Stepping 9, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : The X.Org Foundation (11804000), display 166.111.152.226:0

Fault Count: 1


Assertion in void {anonymous}::mwJavaAbort() at javainit.cpp line 1389:
Fatal Java Exception.  See Java Crash Report for details.

Register State (captured):
  RAX = 00007fb4c3aec390  RBX = 00007fb514084878
  RCX = 0000000000000000  RDX = 00007fb514064c20
  RSP = 00007fb4c3aec2b0  RBP = 00007fb4c3aec670
  RSI = 00007fb513e1b3b8  RDI = 00007fb4c3aec2c0

   R8 = 0000000000000000   R9 = 00007fb5010f58e0
  R10 = 0000000000000000  R11 = 000000000000000f
  R12 = 00007fb5010f51bb  R13 = 00007fb5010f58e0
  R14 = 00007fb5140747e8  R15 = 00007fb4c3aecee0

  RIP = 00007fb513d8859e  EFL = 00007fb4fcdea7c0

   CS = 0029   FS = 0000   GS = 0000

Stack Trace (captured):
[  0] 0x00007fb513d8859e               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01082782 _ZN2fl4diag5linux6x86_6412context_base12capture_dataEv+00000030
[  1] 0x00007fb513d84541               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01066305
[  2] 0x00007fb513d85bd0               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072080
[  3] 0x00007fb513d85c42               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072194
[  4] 0x00007fb5010b675a              /opt/mcr/v901/bin/glnxa64/libmwjmi.so+01099610
[  5] 0x00007fb4f9cd38bb /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08513723
[  6] 0x00007fb4f9b039f2 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06613490
[  7] 0x00007fb49f5cac02   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00011266 NativewindowCommon_FatalError+00000268
[  8] 0x00007fb49f5cb95a   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00014682
[  9] 0x00007fb503bd4d8e              /usr/lib/x86_64-linux-gnu/libX11.so.6+00261518 _XIOError+00000078
[ 10] 0x00007fb503bd261d              /usr/lib/x86_64-linux-gnu/libX11.so.6+00251421 _XEventsQueued+00000125
[ 11] 0x00007fb503bc3f79              /usr/lib/x86_64-linux-gnu/libX11.so.6+00192377 XEventsQueued+00000105
[ 12] 0x00007fb4f3a00d98                                   <unknown-module>+00000000
[ 13] 0x00007fb4f39f41d4                                   <unknown-module>+00000000
[ 14] 0x00007fb4f39f4058                                   <unknown-module>+00000000
[ 15] 0x00007fb4f39f4706                                   <unknown-module>+00000000
[ 16] 0x00007fb4f39ee4e7                                   <unknown-module>+00000000
[ 17] 0x00007fb4f9ab48f5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06289653
[ 18] 0x00007fb4f9ab3358 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284120
[ 19] 0x00007fb4f9ab3627 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284839
[ 20] 0x00007fb4f9ab3747 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06285127
[ 21] 0x00007fb4f9b301d5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06795733
[ 22] 0x00007fb4f9e0dbdf /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800671
[ 23] 0x00007fb4f9e0dce5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800933
[ 24] 0x00007fb4f9cd47f8 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08517624
[ 25] 0x00007fb51b9ef6ba              /lib/x86_64-linux-gnu/libpthread.so.0+00030394
[ 26] 0x00007fb51b72541d                    /lib/x86_64-linux-gnu/libc.so.6+01078301 clone+00000109
[ 27] 0x0000000000000000                                   <unknown-module>+00000000


If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.** This crash report has been saved to disk as /root/matlab_crash_dump.9-1 **



MATLAB is exiting because of fatal error
run_FLLIT.sh: line 30:     9 Killed                  "./FLLIT"
lvhailongdeiMac:~ lvhailong$ 
```

**Comment by farhan8igib** [comment]
Hello I am trying installing FLLIT on my Mac, I have download FLLIT-master on the Desktop from GitHub, this is the path Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨mohammadfarhan⁩ ▸ ⁨Desktop⁩ ▸ ⁨FLLIT-master⁩ ▸ ⁨Compiled

To install the FLLIT I am using the following command line in terminal:

docker run -v /Users/mohammadfarhan/Desktop/FLLIT-master/Compiled/FLLIT -e DISPLAY=10.40.23.152:0 feijianke/fliit

I am getting following response:

Unable to find image 'feijianke/fliit:latest' locally
docker: Error response from daemon: pull access denied for feijianke/fliit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I am already login into Docker and XQuartz is running.

Please help

**Comment by BII-wushuang** [comment]
> Hello I am trying installing FLLIT on my Mac, I have download FLLIT-master on the Desktop from GitHub, this is the path Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨mohammadfarhan⁩ ▸ ⁨Desktop⁩ ▸ ⁨FLLIT-master⁩ ▸ ⁨Compiled
> 
> To install the FLLIT I am using the following command line in terminal:
> 
> docker run -v /Users/mohammadfarhan/Desktop/FLLIT-master/Compiled/FLLIT -e DISPLAY=10.40.23.152:0 feijianke/fliit
> 
> I am getting following response:
> 
> Unable to find image 'feijianke/fliit:latest' locally
> docker: Error response from daemon: pull access denied for feijianke/fliit, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> 
> I am already login into Docker and XQuartz is running.
> 
> Please help

Hi Farhan, please try again with the command
```docker run -v /Users/mohammadfarhan/Desktop/FLLIT-master/Compiled:/FLLIT -e DISPLAY=10.40.23.152:0 feijianke/fllit```

There is a typo for ```fllit``` in your original input.

**Comment by BII-wushuang** [comment]
> Thanks for your reply. Now I can run it on macOS. However, After I clicked the segmentation button. The program used a lot of CPU and then the window was crashed and closed automatically .
> Here is the logs in terminal:
> 
> ```
> Last login: Wed Jul 31 14:58:47 on console
> lvhailongdeiMac:~ lvhailong$ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown
> [1] 540
> lvhailongdeiMac:~ lvhailong$ docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=166.111.152.226:0 feijianke/fllit
> ------------------------------------------
> Setting up environment variables
> ---
> LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
> Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
> Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
> Opening log file:  /root/java.log.9
> FLLIT: javainit.cpp:1389: void {anonymous}::mwJavaAbort(): Assertion `Fatal Java Exception.  See Java Crash Report for details.' failed.
> 
> ------------------------------------------------------------------------
>              Assertion detected at Wed Jul 31 07:19:03 2019
> ------------------------------------------------------------------------
> 
> Configuration:
>   Crash Decoding      : Disabled
>   Crash Mode          : continue (default)
>   Current Graphics Driver: Brian Paul Mesa X11 Version 2.1 Mesa 10.5.2
>   Current Visual      : 0x22 (class 4, depth 24)
>   Default Encoding    : US-ASCII
>   GNU C Library       : 2.23 stable
>   Host Name           : cb40b7649641
>   Java Crash Report   : /root/hs_error_pid9.log
>   Java Log            : /root/java.log.9
>   MATLAB Architecture : glnxa64
>   MATLAB Root         : /opt/mcr/v901
>   MATLAB Version      : 9.0.0.341360 (R2016a)
>   OpenGL              : hardware
>   Operating System    : Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
>   Processor ID        : x86 Family 6 Model 58 Stepping 9, GenuineIntel
>   Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
>   Window System       : The X.Org Foundation (11804000), display 166.111.152.226:0
> 
> Fault Count: 1
> 
> 
> Assertion in void {anonymous}::mwJavaAbort() at javainit.cpp line 1389:
> Fatal Java Exception.  See Java Crash Report for details.
> 
> Register State (captured):
>   RAX = 00007fb4c3aec390  RBX = 00007fb514084878
>   RCX = 0000000000000000  RDX = 00007fb514064c20
>   RSP = 00007fb4c3aec2b0  RBP = 00007fb4c3aec670
>   RSI = 00007fb513e1b3b8  RDI = 00007fb4c3aec2c0
> 
>    R8 = 0000000000000000   R9 = 00007fb5010f58e0
>   R10 = 0000000000000000  R11 = 000000000000000f
>   R12 = 00007fb5010f51bb  R13 = 00007fb5010f58e0
>   R14 = 00007fb5140747e8  R15 = 00007fb4c3aecee0
> 
>   RIP = 00007fb513d8859e  EFL = 00007fb4fcdea7c0
> 
>    CS = 0029   FS = 0000   GS = 0000
> 
> Stack Trace (captured):
> [  0] 0x00007fb513d8859e               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01082782 _ZN2fl4diag5linux6x86_6412context_base12capture_dataEv+00000030
> [  1] 0x00007fb513d84541               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01066305
> [  2] 0x00007fb513d85bd0               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072080
> [  3] 0x00007fb513d85c42               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072194
> [  4] 0x00007fb5010b675a              /opt/mcr/v901/bin/glnxa64/libmwjmi.so+01099610
> [  5] 0x00007fb4f9cd38bb /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08513723
> [  6] 0x00007fb4f9b039f2 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06613490
> [  7] 0x00007fb49f5cac02   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00011266 NativewindowCommon_FatalError+00000268
> [  8] 0x00007fb49f5cb95a   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00014682
> [  9] 0x00007fb503bd4d8e              /usr/lib/x86_64-linux-gnu/libX11.so.6+00261518 _XIOError+00000078
> [ 10] 0x00007fb503bd261d              /usr/lib/x86_64-linux-gnu/libX11.so.6+00251421 _XEventsQueued+00000125
> [ 11] 0x00007fb503bc3f79              /usr/lib/x86_64-linux-gnu/libX11.so.6+00192377 XEventsQueued+00000105
> [ 12] 0x00007fb4f3a00d98                                   <unknown-module>+00000000
> [ 13] 0x00007fb4f39f41d4                                   <unknown-module>+00000000
> [ 14] 0x00007fb4f39f4058                                   <unknown-module>+00000000
> [ 15] 0x00007fb4f39f4706                                   <unknown-module>+00000000
> [ 16] 0x00007fb4f39ee4e7                                   <unknown-module>+00000000
> [ 17] 0x00007fb4f9ab48f5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06289653
> [ 18] 0x00007fb4f9ab3358 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284120
> [ 19] 0x00007fb4f9ab3627 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284839
> [ 20] 0x00007fb4f9ab3747 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06285127
> [ 21] 0x00007fb4f9b301d5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06795733
> [ 22] 0x00007fb4f9e0dbdf /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800671
> [ 23] 0x00007fb4f9e0dce5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800933
> [ 24] 0x00007fb4f9cd47f8 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08517624
> [ 25] 0x00007fb51b9ef6ba              /lib/x86_64-linux-gnu/libpthread.so.0+00030394
> [ 26] 0x00007fb51b72541d                    /lib/x86_64-linux-gnu/libc.so.6+01078301 clone+00000109
> [ 27] 0x0000000000000000                                   <unknown-module>+00000000
> 
> 
> If this problem is reproducible, please submit a Service Request via:
>     http://www.mathworks.com/support/contact_us/
> 
> A technical support engineer might contact you with further information.
> 
> Thank you for your help.** This crash report has been saved to disk as /root/matlab_crash_dump.9-1 **
> 
> 
> 
> MATLAB is exiting because of fatal error
> run_FLLIT.sh: line 30:     9 Killed                  "./FLLIT"
> lvhailongdeiMac:~ lvhailong$ 
> ```

Hi, I suspect the issue to be related to this [reported bug](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1726595). However, I cannot reproduce it on my side. Please give me a while to see what I can do. Thanks.

**Comment by farhan8igib** [comment]
Dear Shuang, Thanks for the quick response and I am running the command, its been 3 hours and nothing is happening. I am attaching here window

![Screen Shot 2019-08-06 at 11 37 26 AM](https://user-images.githubusercontent.com/751900/62524893-1bc73000-b83f-11e9-808b-4941e8fcbffb.png)

I have not closed the window yet, but doesn't look it will work like this. Suggest me if there is any alternative

**Comment by BII-wushuang** [comment]
> Dear Shuang, Thanks for the quick response and I am running the command, its been 3 hours and nothing is happening. I am attaching here window
> 
> ![Screen Shot 2019-08-06 at 11 37 26 AM](https://user-images.githubusercontent.com/751900/62524893-1bc73000-b83f-11e9-808b-4941e8fcbffb.png)
> 
> I have not closed the window yet, but doesn't look it will work like this. Suggest me if there is any alternative

Hi, as in my reply to hailong's question, please make sure that you have already issued the **socat command** in terminal
```socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown```
and **XQuartz is running** before issuing your docker run command

**Comment by farhan8igib** [comment]
Dear Shuang,
I did issued the scot command earlier and again tried this morning. have a look at the screen shot. Is there a possibility that I can use my system using TeamViewer and you can help us in installing?

![Screen Shot 2019-08-07 at 1 16 17 PM](https://user-images.githubusercontent.com/751900/62615429-eb05fa00-b915-11e9-8ad8-4f93fd5224dc.png)

**Comment by lvhailong** [comment]
> > Thanks for your reply. Now I can run it on macOS. However, After I clicked the segmentation button. The program used a lot of CPU and then the window was crashed and closed automatically .
> > Here is the logs in terminal:
> > ```
> > Last login: Wed Jul 31 14:58:47 on console
> > lvhailongdeiMac:~ lvhailong$ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown
> > [1] 540
> > lvhailongdeiMac:~ lvhailong$ docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=166.111.152.226:0 feijianke/fllit
> > ------------------------------------------
> > Setting up environment variables
> > ---
> > LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
> > Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
> > Nativewindow X11 IOError: Display 0x7fb4fdef03f0 (166.111.152.226:0): Resource temporarily unavailable
> > Opening log file:  /root/java.log.9
> > FLLIT: javainit.cpp:1389: void {anonymous}::mwJavaAbort(): Assertion `Fatal Java Exception.  See Java Crash Report for details.' failed.
> > 
> > ------------------------------------------------------------------------
> >              Assertion detected at Wed Jul 31 07:19:03 2019
> > ------------------------------------------------------------------------
> > 
> > Configuration:
> >   Crash Decoding      : Disabled
> >   Crash Mode          : continue (default)
> >   Current Graphics Driver: Brian Paul Mesa X11 Version 2.1 Mesa 10.5.2
> >   Current Visual      : 0x22 (class 4, depth 24)
> >   Default Encoding    : US-ASCII
> >   GNU C Library       : 2.23 stable
> >   Host Name           : cb40b7649641
> >   Java Crash Report   : /root/hs_error_pid9.log
> >   Java Log            : /root/java.log.9
> >   MATLAB Architecture : glnxa64
> >   MATLAB Root         : /opt/mcr/v901
> >   MATLAB Version      : 9.0.0.341360 (R2016a)
> >   OpenGL              : hardware
> >   Operating System    : Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
> >   Processor ID        : x86 Family 6 Model 58 Stepping 9, GenuineIntel
> >   Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
> >   Window System       : The X.Org Foundation (11804000), display 166.111.152.226:0
> > 
> > Fault Count: 1
> > 
> > 
> > Assertion in void {anonymous}::mwJavaAbort() at javainit.cpp line 1389:
> > Fatal Java Exception.  See Java Crash Report for details.
> > 
> > Register State (captured):
> >   RAX = 00007fb4c3aec390  RBX = 00007fb514084878
> >   RCX = 0000000000000000  RDX = 00007fb514064c20
> >   RSP = 00007fb4c3aec2b0  RBP = 00007fb4c3aec670
> >   RSI = 00007fb513e1b3b8  RDI = 00007fb4c3aec2c0
> > 
> >    R8 = 0000000000000000   R9 = 00007fb5010f58e0
> >   R10 = 0000000000000000  R11 = 000000000000000f
> >   R12 = 00007fb5010f51bb  R13 = 00007fb5010f58e0
> >   R14 = 00007fb5140747e8  R15 = 00007fb4c3aecee0
> > 
> >   RIP = 00007fb513d8859e  EFL = 00007fb4fcdea7c0
> > 
> >    CS = 0029   FS = 0000   GS = 0000
> > 
> > Stack Trace (captured):
> > [  0] 0x00007fb513d8859e               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01082782 _ZN2fl4diag5linux6x86_6412context_base12capture_dataEv+00000030
> > [  1] 0x00007fb513d84541               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01066305
> > [  2] 0x00007fb513d85bd0               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072080
> > [  3] 0x00007fb513d85c42               /opt/mcr/v901/bin/glnxa64/libmwfl.so+01072194
> > [  4] 0x00007fb5010b675a              /opt/mcr/v901/bin/glnxa64/libmwjmi.so+01099610
> > [  5] 0x00007fb4f9cd38bb /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08513723
> > [  6] 0x00007fb4f9b039f2 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06613490
> > [  7] 0x00007fb49f5cac02   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00011266 NativewindowCommon_FatalError+00000268
> > [  8] 0x00007fb49f5cb95a   /opt/mcr/v901/bin/glnxa64/libnativewindow_x11.so+00014682
> > [  9] 0x00007fb503bd4d8e              /usr/lib/x86_64-linux-gnu/libX11.so.6+00261518 _XIOError+00000078
> > [ 10] 0x00007fb503bd261d              /usr/lib/x86_64-linux-gnu/libX11.so.6+00251421 _XEventsQueued+00000125
> > [ 11] 0x00007fb503bc3f79              /usr/lib/x86_64-linux-gnu/libX11.so.6+00192377 XEventsQueued+00000105
> > [ 12] 0x00007fb4f3a00d98                                   <unknown-module>+00000000
> > [ 13] 0x00007fb4f39f41d4                                   <unknown-module>+00000000
> > [ 14] 0x00007fb4f39f4058                                   <unknown-module>+00000000
> > [ 15] 0x00007fb4f39f4706                                   <unknown-module>+00000000
> > [ 16] 0x00007fb4f39ee4e7                                   <unknown-module>+00000000
> > [ 17] 0x00007fb4f9ab48f5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06289653
> > [ 18] 0x00007fb4f9ab3358 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284120
> > [ 19] 0x00007fb4f9ab3627 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06284839
> > [ 20] 0x00007fb4f9ab3747 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06285127
> > [ 21] 0x00007fb4f9b301d5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+06795733
> > [ 22] 0x00007fb4f9e0dbdf /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800671
> > [ 23] 0x00007fb4f9e0dce5 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+09800933
> > [ 24] 0x00007fb4f9cd47f8 /opt/mcr/v901/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+08517624
> > [ 25] 0x00007fb51b9ef6ba              /lib/x86_64-linux-gnu/libpthread.so.0+00030394
> > [ 26] 0x00007fb51b72541d                    /lib/x86_64-linux-gnu/libc.so.6+01078301 clone+00000109
> > [ 27] 0x0000000000000000                                   <unknown-module>+00000000
> > 
> > 
> > If this problem is reproducible, please submit a Service Request via:
> >     http://www.mathworks.com/support/contact_us/
> > 
> > A technical support engineer might contact you with further information.
> > 
> > Thank you for your help.** This crash report has been saved to disk as /root/matlab_crash_dump.9-1 **
> > 
> > 
> > 
> > MATLAB is exiting because of fatal error
> > run_FLLIT.sh: line 30:     9 Killed                  "./FLLIT"
> > lvhailongdeiMac:~ lvhailong$ 
> > ```
> 
> Hi, I suspect the issue to be related to this [reported bug](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1726595). However, I cannot reproduce it on my side. Please give me a while to see what I can do. Thanks.

Hi shuang, I have successfully run it through for one time. However, sometimes I got this "Address already in use" error. Can you help me analyze the reason?
```
rmbp:~ lvhailong$ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" & disown
[1] 1693
rmbp:~ lvhailong$ 2019/08/08 14:52:21 socat[1693] E bind(5, {LEN=0 AF=2 0.0.0.0:6000}, 16): Address already in use

```

**Comment by BII-wushuang** [comment]
> Hi shuang, I have successfully run it through for one time. However, sometimes I got this "Address already in use" error. Can you help me analyze the reason?

Hi Hailong, the socat command need to be issued only once before you issue the docker run command. In this case, the socat command sets up a port 6000 to receive data streams relayed to this port from docker (docker is like a lightweight virtual machine). Issuing the socat command again will result in the **Address already in use** error.

To resolve it, you can kill the socat process by issuing
```kill socat_process_id```
For example, in ur screenshot above, the socat pid would be ```1693```.
If the socat pid is not there, you can obtain your socat pid by issuing 
```ps -ax | grep socat```

**Comment by BII-wushuang** [comment]
> Dear Shuang,
> I did issued the scot command earlier and again tried this morning. have a look at the screen shot. Is there a possibility that I can use my system using TeamViewer and you can help us in installing?
> 
> ![Screen Shot 2019-08-07 at 1 16 17 PM](https://user-images.githubusercontent.com/751900/62615429-eb05fa00-b915-11e9-8ad8-4f93fd5224dc.png)

Hi Farhan, sure no problem. It would be better for you to drop me an email at wushuang@bii.a-star.edu.sg so that we can make the team viewer arrangements.

**Comment by lvhailong** [comment]
> > Hi shuang, I have successfully run it through for one time. However, sometimes I got this "Address already in use" error. Can you help me analyze the reason?
> 
> Hi Hailong, the socat command need to be issued only once before you issue the docker run command. In this case, the socat command sets up a port 6000 to receive data streams relayed to this port from docker (docker is like a lightweight virtual machine). Issuing the socat command again will result in the **Address already in use** error.
> 
> To resolve it, you can kill the socat process by issuing
> `kill socat_process_id`
> For example, in ur screenshot above, the socat pid would be `1693`.
> If the socat pid is not there, you can obtain your socat pid by issuing
> `ps -ax | grep socat`

Many thanks for your quick reply. I found the cause of the problem. The steps are sequential. If you run xquartz before running this command, you will get an error. Now I can run through the analysis process using the sample data provided. But when I switched to my own data, another error occurred.

```
rmbp:~ lvhailong$ docker run -v /Users/lvhailong/FLLIT-master/Compiled:/FLLIT -e DISPLAY=172.30.78.37:0 feijianke/fllit
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
Error using bwmorph
Expected input number 1, BW, to be two-dimensional.

Error in bwmorph (line 90)


Error in leg_segment (line 22)


Error in FLLIT>Segmentation_Callback (line 893)
```

I have converted video to tif image sequence and provided Background/ background.png
This is [a small part of my data.](http://97.107.136.61/w1118.zip)

**Comment by eddie2612** [comment]
Dear Shuang,

I'm getting the same issue as Hailong after segmentation. Provided a Background image but FLLIT returns a blank white square when I initiate segmentation then the code below:


`Setting up environment variables

LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
Error using bwmorph
Expected input number 1, BW, to be two-dimensional.

Error in bwmorph (line 90)


Error in leg_segment (line 22)


Error in FLLIT>Segmentation_Callback (line 918)


Error in gui_mainfcn (line 95)


Error in FLLIT (line 46)


Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FLLIT('Segmentation_Callback',hObject,eventdata,guidata(hObject))


Error while evaluating UIControl Callback`

**Comment by BII-wushuang** [comment]
> Dear Shuang,
> 
> I'm getting the same issue as Hailong after segmentation. Provided a Background image but FLLIT returns a blank white square when I initiate segmentation then the code below:
> 
> `Setting up environment variables
> 
> LD_LIBRARY_PATH is .:/opt/mcr/v901/runtime/glnxa64:/opt/mcr/v901/bin/glnxa64:/opt/mcr/v901/sys/os/glnxa64:/opt/mcr/v901/sys/opengl/lib/glnxa64
> Error using bwmorph
> Expected input number 1, BW, to be two-dimensional.
> 
> Error in bwmorph (line 90)
> 
> Error in leg_segment (line 22)
> 
> Error in FLLIT>Segmentation_Callback (line 918)
> 
> Error in gui_mainfcn (line 95)
> 
> Error in FLLIT (line 46)
> 
> Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FLLIT('Segmentation_Callback',hObject,eventdata,guidata(hObject))
> 
> Error while evaluating UIControl Callback`

Sorry for the late reply. I have rectified this issue.
