### ISSUE TITLE
Error in FLLIT>Tracking_Callback

### ISSUE THREAD

**Issue by lvhailong** [BII-wushuang/FLLIT#4]
Sometimes I got this error after the segmentation finished. And it will not start leg tracking.

```
Index exceeds matrix dimensions.

Error in FLLIT>Tracking_Callback (line 1384)


Error in FLLIT>Segmentation_Callback (line 1058)


Error in gui_mainfcn (line 95)


Error in FLLIT (line 46)


Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FLLIT('Segmentation_Callback',hObject,eventdata,guidata(hObject))


Error while evaluating UIControl Callback


```

**Comment by lacinh** [comment]
i have the same problem here. any solution?

**Comment by lacinh** [comment]
I am using Ubuntu (installed it just for this program); I used the provided data (yw 35d male-1-2up_H2). I have the same error indicated by  lvhailong.

**Comment by BII-wushuang** [comment]
I have resolved this issue in the latest commit.

**Comment by lacinh** [comment]
thanks; I will try again.
best
Haluk

**Comment by lacinh** [comment]
Hi Shuang,
I tried again after installing ubuntu focal fossa. Now, I cannot get into
FLLIT at all.Could you please give me a suggestion?
thanks

Here is the command and error.







*haluk@haluk-home:~/FLLIT/Compiled$ bash run_FLLIT.sh
$HOME/MCR/v901------------------------------------------Setting up
environment variables---LD_LIBRARY_PATH is
.:/home/haluk/MCR/v901/runtime/glnxa64:/home/haluk/MCR/v901/bin/glnxa64:/home/haluk/MCR/v901/sys/os/glnxa64:/home/haluk/MCR/v901/sys/opengl/lib/glnxa64Error
in extracting CTF file to '/home/haluk/.mcrCache9.0.1/FLLIT_0'. Details:
'Could not close zip entry that was open for read'Could not access the
MATLAB Runtime component cache.haluk@haluk-home:~/FLLIT/Compiled$ *

**Comment by lacinh** [comment]
Hi Shuang,
I was able to open GUI but failed at loading data. I tried two different
sets from your data. It did not show any image in the main window.
thanks for trying to help
best
Haluk

**Comment by lvhailong** [comment]
> I have resolved this issue in the latest commit.

I tried to install the latest version of the program on the ubuntu system. But still I got similar problems. 
I would like to know whether the unmarked feet in the automatic identification process must be clearly marked manually before subsequent analysis, and if less than 6 feet in some of the frames cause the program to report an error and stop running?

**Comment by sly724** [comment]
Hi Shuang,
I am using Ubuntu; I used the provided data (spider male-1-1-20230202T121258Z-001). I have the same error.

Operands to the || and && operators must be convertible to logical scalar values.
Error in FLLIT>Tracking_Callback (line 1270)
Error in FLLIT>Segmentation_Callback (line 1035)
Error in gui_mainfcn (line 95)
Error in FLLIT (line 46)
Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)FLLIT('Segmentation_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback

Could you please give me a suggestion?
